{#- Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-#}
{%- macro pit(
    satellites,
    src_pk, 
    src_hashdiff,
    src_eff,
    src_ldts, 
    src_source,
    src_db
    ) -%}

    {{- adapter_macro(
        'dbtvault.pit', 
        satellites=satellites,
        src_pk=src_pk, 
        src_hashdiff=src_hashdiff,
        src_eff=src_eff,    
        src_ldts=src_ldts, 
        src_source=src_source,
        src_db=src_db) }}

{%- endmacro %}

{%- macro default__pit(
    satellites,
    src_pk, 
    src_hashdiff,
    src_eff,
    src_ldts, 
    src_source,
    src_db
    ) -%}

{%- set source_cols = dbtvault.expand_column_list(
    columns=[
        src_pk, 
        src_hashdiff,
        src_eff,
        src_ldts, 
        src_source,
        src_db
        ]) -%}

-- Generated by dbtvault
WITH LOAD_DATES as (
{%- for sat in satellites -%}
    select distinct 
        {{src_pk}} ,
        {{src_ldts}},
        {{src_source}}
    from 
        {{src_db}}.{{sat}} as e
    {% if not loop.last -%}
    union all
    {% endif -%}
{% endfor -%}
) 
select 
    LD.{{src_pk}},
    LD.{{src_ldts}},
    '' as HASHDIFF,
    LD.{{src_source}},
    lag(LD.{{src_ldts}} )
        OVER (
            PARTITION by ld.{{src_pk}}
            order by ld.{{src_ldts}}
        ) as EFFECTIVE_FROM,
    {% for sat in satellites -%}
    max({{sat}}.{{src_ldts}})
        OVER (
            PARTITION BY
                LD.{{src_pk}} 
            order by
                LD.{{src_ldts}}
            ) as {{sat}}_{{src_ldts}}{% if not loop.last -%},
    {% endif -%}
    {% endfor %}
    
from LOAD_DATES LD
    {% for sat in satellites -%}
    left join {{src_db}}.{{sat}}
        on 
            LD.{{src_pk}} = {{sat}}.{{src_pk}}
    {% endfor -%}
{% endmacro %}
