name: dbtvault_test
version: '0.7'
require-dbt-version: ['>=0.18.0', '<0.19.0']
config-version: 1

profile: dbtvault

source-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
data-paths: [data]
macro-paths: [macros]

target-path: target
clean-targets:
  - target
  - dbt_modules

models:
  dbtvault_test:
    unit:
      schema: "{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_JOB', '') if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"
      staging:
        hash_columns:
          vars:
            columns:
              BOOKING_PK: BOOKING_REF
              CUSTOMER_PK: CUSTOMER_ID
              CUSTOMER_BOOKING_PK:
                - CUSTOMER_ID
                - BOOKING_REF
              BOOK_CUSTOMER_HASHDIFF:
                is_hashdiff: true
                columns:
                  - PHONE
                  - NATIONALITY
                  - CUSTOMER_ID
              BOOK_BOOKING_HASHDIFF:
                is_hashdiff: true
                columns:
                  - BOOKING_REF
                  - BOOKING_DATE
                  - DEPARTURE_DATE
                  - PRICE
                  - DESTINATION
          test_hash_columns_correctly_generates_sql_with_constants_from_yaml:
            vars:
              columns:
                BOOKING_PK: BOOKING_REF
                CUSTOMER_PK:
                  - CUSTOMER_ID
                  - '!9999-12-31'
                CUSTOMER_BOOKING_PK:
                  - CUSTOMER_ID
                  - BOOKING_REF
                  - TO_DATE('9999-12-31')
                BOOK_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - PHONE
                    - NATIONALITY
                    - CUSTOMER_ID
                BOOK_BOOKING_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - BOOKING_REF
                    - TO_DATE('9999-12-31')
                    - '!STG'
                    - BOOKING_DATE
                    - DEPARTURE_DATE
                    - PRICE
                    - DESTINATION
          test_hash_columns_raises_warning_if_mapping_without_hashdiff:
            vars:
              columns:
                BOOKING_PK: BOOKING_REF
                CUSTOMER_PK: CUSTOMER_ID
                CUSTOMER_BOOKING_PK:
                  - CUSTOMER_ID
                  - BOOKING_REF
                BOOK_CUSTOMER_HASHDIFF:
                  columns:
                    - PHONE
                    - NATIONALITY
                    - CUSTOMER_ID
                BOOK_BOOKING_HASHDIFF:
                  columns:
                    - BOOKING_REF
                    - BOOKING_DATE
                    - DEPARTURE_DATE
                    - PRICE
                    - DESTINATION
        stage:
          test_stage_correctly_generates_sql_from_yaml:
            vars:
              source_model: raw_source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUST_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_DOB
                    - CUSTOMER_ID
                    - CUSTOMER_NAME
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_ID
                    - NATIONALITY
                    - PHONE
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: BOOKING_DATE
          test_stage_correctly_generates_sql_from_yaml_with_source_style:
            vars:
              source_model:
                test_unit: source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUST_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_DOB
                    - CUSTOMER_ID
                    - CUSTOMER_NAME
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_ID
                    - NATIONALITY
                    - PHONE
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: LOADDATE
          test_stage_correctly_generates_sql_for_only_source_columns_from_yaml:
            vars:
              include_source_columns: true
              source_model: raw_source
          test_stage_correctly_generates_sql_for_only_source_columns_and_missing_flag_from_yaml:
            vars:
              source_model: raw_source
          test_stage_correctly_generates_sql_for_only_derived_from_yaml:
            vars:
              include_source_columns: false
              source_model: raw_source
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: LOAD_DATETIME
          test_stage_correctly_generates_sql_for_only_hashing_from_yaml:
            vars:
              include_source_columns: false
              source_model: raw_source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUST_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_DOB
                    - CUSTOMER_ID
                    - CUSTOMER_NAME
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_ID
                    - NATIONALITY
                    - PHONE
          test_stage_correctly_generates_sql_for_hashing_and_source_from_yaml:
            vars:
              source_model: raw_source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUST_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_DOB
                    - CUSTOMER_ID
                    - CUSTOMER_NAME
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_ID
                    - NATIONALITY
                    - PHONE
          test_stage_raises_error_with_missing_source:
            vars:
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUST_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_DOB
                    - CUSTOMER_ID
                    - CUSTOMER_NAME
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_ID
                    - NATIONALITY
                    - PHONE
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: LOADDATE
          test_stage_correctly_generates_sql_for_derived_and_source_from_yaml:
            vars:
              source_model: raw_source
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: BOOKING_DATE
          test_stage_correctly_generates_sql_for_hashing_and_derived_from_yaml:
            vars:
              include_source_columns: false
              source_model: raw_source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUST_CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_DOB
                    - CUSTOMER_ID
                    - CUSTOMER_NAME
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  columns:
                    - CUSTOMER_ID
                    - NATIONALITY
                    - PHONE
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: BOOKING_DATE
          test_stage_correctly_generates_sql_for_hashing_with_exclude_flag:
            vars:
              source_model: raw_source
              derived_columns:
                SOURCE: '!STG_BOOKING'
                EFFECTIVE_FROM: LOADDATE
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  exclude_columns: true
                  columns:
                    - BOOKING_FK
                    - ORDER_FK
                    - CUSTOMER_PK
                    - LOADDATE
                    - RECORD_SOURCE
          test_stage_correctly_generates_sql_for_only_hashing_with_exclude_flag:
            vars:
              include_source_columns: false
              source_model: raw_source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  exclude_columns: true
                  columns:
                    - BOOKING_FK
                    - ORDER_FK
                    - CUSTOMER_PK
                    - LOADDATE
                    - RECORD_SOURCE
          test_stage_correctly_generates_sql_for_only_source_and_hashing_with_exclude_flag:
            vars:
              source_model: raw_source
              hashed_columns:
                CUSTOMER_PK: CUSTOMER_ID
                CUSTOMER_HASHDIFF:
                  is_hashdiff: true
                  exclude_columns: true
                  columns:
                    - BOOKING_FK
                    - ORDER_FK
                    - CUSTOMER_PK
                    - LOADDATE
                    - RECORD_SOURCE
      tables:
        hub:
          materialized: incremental
          test_hub_macro_correctly_generates_sql_for_single_source:
            vars:
              source_model: raw_source
              src_pk: CUSTOMER_PK
              src_nk: CUSTOMER_ID
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_single_source_multi_nk:
            vars:
              source_model: raw_source
              src_pk: CUSTOMER_PK
              src_nk:
                - CUSTOMER_ID
                - CUSTOMER_NAME
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_incremental_single_source:
            vars:
              source_model: raw_source
              src_pk: CUSTOMER_PK
              src_nk: CUSTOMER_ID
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_incremental_single_source_multi_nk:
            vars:
              source_model: raw_source
              src_pk: CUSTOMER_PK
              src_nk:
                - CUSTOMER_ID
                - CUSTOMER_NAME
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_multi_source:
            vars:
              source_model:
                - raw_source
                - raw_source_2
              src_pk: CUSTOMER_PK
              src_nk: CUSTOMER_ID
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_multi_source_multi_nk:
            vars:
              source_model:
                - raw_source
                - raw_source_2
              src_pk: CUSTOMER_PK
              src_nk:
                - CUSTOMER_ID
                - CUSTOMER_NAME
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_incremental_multi_source:
            vars:
              source_model:
                - raw_source
                - raw_source_2
              src_pk: CUSTOMER_PK
              src_nk: CUSTOMER_ID
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_hub_macro_correctly_generates_sql_for_incremental_multi_source_multi_nk:
            vars:
              source_model:
                - raw_source
                - raw_source_2
              src_pk: CUSTOMER_PK
              src_nk:
                - CUSTOMER_ID
                - CUSTOMER_NAME
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
        link:
          materialized: incremental
          test_link_macro_correctly_generates_sql_for_single_source:
            vars:
              source_model: raw_source
              src_pk: CUSTOMER_PK
              src_fk:
                - ORDER_FK
                - BOOKING_FK
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_link_macro_correctly_generates_sql_for_incremental_single_source:
            vars:
              source_model: raw_source
              src_pk: CUSTOMER_PK
              src_fk:
                - ORDER_FK
                - BOOKING_FK
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_link_macro_correctly_generates_sql_for_multi_source:
            vars:
              source_model:
                - raw_source
                - raw_source_2
              src_pk: CUSTOMER_PK
              src_fk:
                - ORDER_FK
                - BOOKING_FK
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
          test_link_macro_correctly_generates_sql_for_incremental_multi_source:
            vars:
              source_model:
                - raw_source
                - raw_source_2
              src_pk: CUSTOMER_PK
              src_fk:
                - ORDER_FK
                - BOOKING_FK
              src_ldts: LOADDATE
              src_source: RECORD_SOURCE
    feature:
      schema: "{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_JOB', '') if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"
  vars:
    max_date: TO_DATE("9999-12-31")

seeds:
  schema: "{{ env_var('SNOWFLAKE_DB_USER') }}{{ '_' ~ env_var('CIRCLE_JOB', '') if env_var('CIRCLE_JOB', '') }}{{ '_' ~ env_var('CIRCLE_NODE_INDEX', '') if env_var('CIRCLE_NODE_INDEX', '') }}"
  quote_columns: true
  dbtvault_test:
    raw_source:
      column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOADDATE: DATE
    raw_source_2:
      column_types:
        CUSTOMER_PK: BINARY(16)
        BOOKING_FK: BINARY(16)
        ORDER_FK: BINARY(16)
        LOADDATE: DATE